const PUSHER_APP_ID = "";
const PUSHER_APP_KEY = "";
const PUSHER_APP_SECRET = "";

const FIREBASE_API_KEY = "";
const FIREBASE_MESSAGING_SENDER_ID = "";
const FIREBASE_APP_ID = "";

export {
  PUSHER_APP_ID,
  PUSHER_APP_KEY,
  PUSHER_APP_SECRET,
  FIREBASE_API_KEY,
  FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID,
};
